-- schema and seed for base.db
DROP TABLE IF EXISTS PIATTO_TABLE;
CREATE TABLE PIATTO_TABLE (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOME_PIATTO TEXT, PORTATA_PIATTO TEXT, NUTRIENTI_PIATTO TEXT, FAVORITO INTEGER DEFAULT 0);

INSERT INTO PIATTO_TABLE (NOME_PIATTO, PORTATA_PIATTO, NUTRIENTI_PIATTO, FAVORITO) VALUES ('Spaghetti al pomodoro','Primo','Altro',0);
INSERT INTO PIATTO_TABLE (NOME_PIATTO, PORTATA_PIATTO, NUTRIENTI_PIATTO, FAVORITO) VALUES ('Insalata mista','Contorno','Altro',0);
INSERT INTO PIATTO_TABLE (NOME_PIATTO, PORTATA_PIATTO, NUTRIENTI_PIATTO, FAVORITO) VALUES ('Pollo al forno','Secondo','Carne Bianca',0);
INSERT INTO PIATTO_TABLE (NOME_PIATTO, PORTATA_PIATTO, NUTRIENTI_PIATTO, FAVORITO) VALUES ('Salmone alla griglia','Secondo','Pesce',0);
INSERT INTO PIATTO_TABLE (NOME_PIATTO, PORTATA_PIATTO, NUTRIENTI_PIATTO, FAVORITO) VALUES ('Ratatouille','Contorno','Altro',0);
