-- schema and seed for base.db
DROP TABLE IF EXISTS PIATTO_TABLE;
CREATE TABLE PIATTO_TABLE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    NOME_PIATTO TEXT, 
    PORTATA_PIATTO TEXT, 
    NUTRIENTI_PIATTO TEXT, 
    FAVORITO INTEGER DEFAULT 0,
    DOMINANZA_NUTRIZIONALE TEXT,
    PROFILO_GUSTATIVO TEXT
);

INSERT INTO PIATTO_TABLE (NOME_PIATTO, PORTATA_PIATTO, NUTRIENTI_PIATTO, FAVORITO, DOMINANZA_NUTRIZIONALE, PROFILO_GUSTATIVO) VALUES 
('Spaghetti aglio, olio e peperoncino', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Spaghetti al pomodoro e basilico', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Bucatini all''amatriciana', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Spaghetti alla carbonara', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Rigatoni alla gricia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tonnarelli cacio e pepe', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Penne all''arrabbiata', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Trofie al pesto genovese (tradizionalmente con patate e fagiolini)', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Tagliatelle al ragù bolognese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Lasagne al forno', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tortellini in brodo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ziti al ragù napoletano', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ziti alla genovese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Gnocchi alla sorrentina', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pasta e patate (con provola)', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pasta e fagioli', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pasta e ceci', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pasta e lenticchie', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pasta e piselli', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Minestrone di verdure', 'Primo', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Spaghetti alle vongole', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Linguine allo scoglio', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Spaghetti alla puttanesca', 'Primo', 'Pesce', 0, 'Carbo-Puro', 'Mare'),
('Spaghetti alla Nerano', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pasta alla Norma', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Orecchiette alle cime di rapa', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Busiate al pesto trapanese', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pasta con le sarde', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Anelletti al forno', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Malloreddus alla campidanese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Culurgiones al burro e salvia', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pansoti con salsa di noci', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Agnolotti del plin al sugo d''arrosto', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Casoncelli alla bergamasca', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Pizzoccheri alla valtellinese', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Canederli in brodo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Spätzle panna e speck', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Passatelli in brodo', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Maccheroni alla chitarra con pallottine', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Risotto alla milanese', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Risotto ai funghi porcini', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Terra-Forte'),
('Risotto al radicchio e gorgonzola', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Risotto agli asparagi', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Risotto alla pescatora', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Risotto alla zucca', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Risi e bisi', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Penne alla vodka', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Farfalle panna e salmone', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Penne alla boscaiola', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Maccheroni ai quattro formaggi', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Gnocchi al gorgonzola', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Gnocchi al ragù', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ravioli ricotta e spinaci burro e salvia', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Cannelloni di carne al forno', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Calamarata', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Fregola con le arselle', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Pici all''aglione', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Pappardelle al ragù di cinghiale', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ribollita', 'Primo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Pappa al pomodoro', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Zuppa di farro', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Gramigna alla salsiccia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Mezze maniche alla norcina', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Strangozzi al tartufo nero', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Terra-Forte'),
('Tajarin al tartufo bianco', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Terra-Forte'),
('Paniscia novarese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Pasta e cavolfiore', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Pasta e zucca', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Sedani con panna, prosciutto e piselli', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Spaghetti al tonno', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Penne zucchine e gamberetti', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Linguine all''astice', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Spaghetti con le cozze', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Risotto al nero di seppia', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Paccheri ai frutti di mare', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Fusilli peperoni e olive', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Spaghetti ai ricci di mare', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Pasta fredda (pomodorini, mozzarella, olive)', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Insalata di riso', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Orecchiette pomodoro e cacioricotta', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Gnocchi alla bava', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Maltagliati ai fagioli', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Bucatini coi cavolfiori alla siciliana', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Cavatelli con i broccoli', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Timballo di maccheroni', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Strozzapreti cannocchie e pomodorini', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Spaghetti con le telline', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Zuppa di lenticchie', 'Primo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Crema di zucca', 'Primo', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Pasta e fagioli con le cozze', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Tubetti in brodo di gallina', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Paccheri con sugo di coccio', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Casarecce pesce spada e melanzane', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Gnocchetti sardi pomodoro e salsiccia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Scialatielli ai frutti di mare', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Mafalde con ricotta e pomodoro', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Spaghetti alla carrettiera', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Penne al baffo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tagliatelle ai funghi misti', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Terra-Forte'),
('Risotto allo zafferano e salsiccia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Agnolotti pavesi', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Anolini in brodo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Bigoli in salsa', 'Primo', 'Pesce', 0, 'Carbo-Puro', 'Mare'),
('Cappelletti in brodo di cappone', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Casoncelli bresciani', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Cialzons', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Corzetti al sugo di carne', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Garganelli panna, piselli e prosciutto', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Gnocchi di susine', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Minestra d''orzo trentina', 'Primo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Panissa vercellese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Pisarei e faśö', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Risotto al Tastasal', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Risotto all''Amarone', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Terra-Forte'),
('Risotto all''isolana', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Risotto con la luganega', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tajarin al ragù di fegatini', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tortelli alle erbette', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Tortelli di zucca mantovani', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Acquacotta', 'Primo', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Fettuccine alla papalina', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Maccheroncini di Campofilone', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Minestra di broccoli e arzilla', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Pappardelle alla lepre', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Sagne e fagioli', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Scrippelle ''mbusse', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Spaghetti alla checca', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Strangozzi (o Stringozzi) al ragù di agnello', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Testaroli al pesto', 'Primo', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Umbricelli al rancetto', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Vincisgrassi', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Zuppa frantoiana', 'Primo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Cavatelli cozze e fagioli', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Ciceri e tria', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Ferretti con mollica e cruschi', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Lagane e cicciari', 'Primo', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Maccheroni al ferretto con ragù lucano', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Orecchiette al ragù di braciole', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Spaghetti ai polipetti affogati', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Spaghetti alle vongole fujute', 'Primo', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Struncatura ammollicata', 'Primo', 'Pesce', 0, 'Carbo-Puro', 'Mare'),
('Tiella di riso, patate e cozze', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Tubetti con i totani', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Ziti lardiati', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Busiate al ragù di tonno', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Cuscus di pesce alla trapanese', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Fregola con salsiccia e zafferano', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Lorighittas al ragù di pollo ruspante', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Maccarrones de busa', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Pasta alla Paolina', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Pasta ca nunnata', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Spaghetti alla bottarga', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Zuppa gallurese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Bistecca di manzo ai ferri', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Cotoletta panata alla milanese', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Scaloppine ai funghi', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Petto di pollo alla griglia', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Polpette di carne al sugo', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Polpette di carne fritte', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Polpettone al forno', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Spezzatino con patate', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Arrosto di vitello', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Involtini di carne ripieni', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Salsiccia in padella', 'Secondo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Hamburger di carne', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Cosce di pollo al forno', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Orata al cartoccio', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Frittura di calamari e gamberi', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Trancio di salmone in padella', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Seppie con piselli', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Merluzzo in umido con pomodorini', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Frittata di cipolle', 'Secondo', 'Proteine Vegetali', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Uova al tegamino', 'Secondo', 'Proteine Vegetali', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Caprese di mozzarella e pomodoro', 'Secondo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Straccetti di manzo con rucola', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Pesce spada alla griglia', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Sgombro al forno', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Braciola di maiale', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Fesa di tacchino arrosto', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Bresaola con rucola e grana', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Prosciutto e melone', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Zucchine ripiene di carne', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Peperoni ripieni', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Roast beef all''inglese', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Insalata di mare', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Impepata di cozze', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Tonno scottato', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Spiedini di carne mista', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Faraona al forno', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Coniglio alla cacciatora', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Vitello tonnato', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Polpo con patate', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Calamari ripieni', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Gamberoni al forno', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Sogliola al burro', 'Secondo', 'Pesce', 0, 'Fibre/Grassi', 'Mare'),
('Tagliata di manzo', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Alici marinate', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Moscardini in umido', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Filetto di manzo al pepe verde', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Lonza di maiale arrosto', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Petto di tacchino in padella', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Carpaccio di manzo', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Tartare di manzo', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Cordon bleu di carne', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Costine di maiale al forno', 'Secondo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Branzino all''acqua pazza', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Alici fritte', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Calamari in padella', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Salsiccia e patate al forno', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tomino alla piastra', 'Secondo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Scamorza alla griglia', 'Secondo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Uova sode ripiene', 'Secondo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Uova strapazzate', 'Secondo', 'Proteine Vegetali', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Frittata di zucchine', 'Secondo', 'Proteine Vegetali', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Cotechino con lenticchie', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Melanzane ripiene di carne', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Sogliola alla mugnaia', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Pesce finto di tonno e patate', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Hamburger di pollo', 'Secondo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Bistecca di tacchino', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Filetto di maiale arrosto', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Nodini di vitello al burro', 'Secondo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Uova in camicia', 'Secondo', 'Proteine Vegetali', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Sarde alla piastra', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Filetto di platessa impanato', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Seppie arrosto', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Soutè di cozze e vongole', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Cotoletta di maiale', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Stinco di maiale al forno', 'Secondo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Rollè di tacchino ripieno', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Sovracosce di pollo in padella', 'Secondo', 'Carne Bianca', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Bastoncini di pesce impanati', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Trancio di tonno al forno', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Fegato alla veneziana', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Arrosticini di pecora', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Coda alla vaccinara', 'Secondo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Saltimbocca alla romana', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Baccalà alla vicentina', 'Secondo', 'Pesce', 0, 'Fibre/Grassi', 'Mare'),
('Porceddu sardo', 'Secondo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Fritto misto alla piemontese', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Sarde in saor', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Braciole alla messinese', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Trippa alla fiorentina', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Bombette pugliesi', 'Secondo', 'Carne Rossa', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Peposo dell''Impruneta', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Ossobuco alla milanese', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Cima alla genovese', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Frico friulano', 'Secondo', 'Proteine Vegetali', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Triglie alla livornese', 'Secondo', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Involtini di pesce spada alla siciliana', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Gulasch trentino', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Pollo alla romana', 'Secondo', 'Carne Bianca', 0, 'Proteina-Pura', 'Terra-Forte'),
('Brasato al Barolo', 'Secondo', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Patate al forno', 'Contorno', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Patate fritte', 'Contorno', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Purè di patate', 'Contorno', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Insalata di patate', 'Contorno', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Patate in padella', 'Contorno', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Zucchine alla griglia', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Melanzane a funghetto', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Peperonata', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Spinaci saltati in padella', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Cicoria ripassata', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Fagiolini lessi', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Funghi trifolati', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Cime di rapa stufate', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Bieta all''agro', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Carciofi alla romana', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Piselli in umido', 'Contorno', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Zucchine trifolate', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Finocchi gratinati', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Cavolfiore gratinato', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Zucca al forno', 'Contorno', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Pomodori gratinati', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Verdure miste al forno', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Fagioli all''uccelletto', 'Contorno', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Lenticchie in umido', 'Contorno', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ceci in insalata', 'Contorno', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Insalata mista', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Insalata di finocchi', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Insalata di pomodori', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Puntarelle alla romana', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Mare'),
('Melanzane sott''olio', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Zucchine alla scapece', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Giardiniera di verdure', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Carciofini sott''olio', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Terra-Forte'),
('Cipolline in agrodolce', 'Contorno', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Pizza', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Pinsa romana', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Focaccia ripiena', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Panzerotti pugliesi', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Piadina romagnola', 'Piatto Unico', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Tigelle con salumi e formaggi', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Torta al testo', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Crescia', 'Piatto Unico', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Panino con panelle', 'Piatto Unico', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Panino con salumi', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Pani ca meusa', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tramezzino', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Toast', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Club sandwich', 'Piatto Unico', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Farinata di ceci', 'Piatto Unico', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Gateau di patate', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Torta pasqualina', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Quiche lorraine', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Torta salata ricotta e spinaci', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Strudel salato', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Danubio salato', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Babà rustico', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Casatiello', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Lasagna', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Cannelloni', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Sartù di riso', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Timballo di anelletti', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Pasta al forno', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Vincisgrassi', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Frittata di pasta', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Melanzane ripiene', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Peperoni ripieni', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ragù napoletano', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Bollito misto con brodo', 'Piatto Unico', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Cacciucco alla livornese', 'Piatto Unico', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Brodetto di pesce', 'Piatto Unico', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Seppie con piselli', 'Piatto Unico', 'Pesce', 0, 'Proteina-Pura', 'Mare'),
('Spezzatino con patate', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Insalata di riso', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Insalata di pasta', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Panzanella', 'Piatto Unico', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Frisella condita', 'Piatto Unico', 'Neutro', 0, 'Carbo-Puro', 'Neutro/Orto'),
('Insalatona mista', 'Piatto Unico', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Caprese', 'Piatto Unico', 'Neutro', 0, 'Fibre/Grassi', 'Neutro/Orto'),
('Prosciutto e melone', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Carpaccio con rucola e grana', 'Piatto Unico', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Cous cous freddo', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Insalata nizzarda', 'Piatto Unico', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Polenta concia', 'Piatto Unico', 'Neutro', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Polenta e salsiccia', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ribollita', 'Piatto Unico', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Minestrone con cereali', 'Piatto Unico', 'Proteine Vegetali', 0, 'Carbo-Proteico', 'Neutro/Orto'),
('Trippa alla romana', 'Piatto Unico', 'Carne Rossa', 0, 'Proteina-Pura', 'Terra-Forte'),
('Frittata di verdure', 'Piatto Unico', 'Neutro', 0, 'Proteina-Pura', 'Neutro/Orto'),
('Hamburger', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Hot dog', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Kebab', 'Piatto Unico', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Burritos', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Tacos', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Poke bowl con Salmone', 'Piatto Unico', 'Pesce', 0, 'Carbo-Proteico', 'Mare'),
('Bao di carne', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Ravioli al vapore di carne(Jiaozi)', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Paella valenciana', 'Piatto Unico', 'Carne Bianca', 0, 'Carbo-Proteico', 'Terra-Forte'),
('Moussaka', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Terra-Forte');
