-- schema and seed for base.db
DROP TABLE IF EXISTS PIATTO_TABLE;
CREATE TABLE PIATTO_TABLE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    NOME_PIATTO TEXT, 
    PORTATA_PIATTO TEXT, 
    NUTRIENTI_PIATTO TEXT, 
    FAVORITO INTEGER DEFAULT 0,
    DOMINANZA_NUTRIZIONALE TEXT,
    PROFILO_GUSTATIVO TEXT
);

INSERT INTO PIATTO_TABLE (NOME_PIATTO, PORTATA_PIATTO, NUTRIENTI_PIATTO, FAVORITO, DOMINANZA_NUTRIZIONALE, PROFILO_GUSTATIVO) VALUES 
('Spaghetti aglio, olio e peperoncino', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Spaghetti al pomodoro e basilico', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Bucatini all''amatriciana', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Spaghetti alla carbonara', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Rigatoni alla gricia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Tonnarelli cacio e pepe', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Penne all''arrabbiata', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Trofie al pesto genovese (tradizionalmente con patate e fagiolini)', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Tagliatelle al ragù bolognese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Lasagne al forno', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Tortellini in brodo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Ziti al ragù napoletano', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Ziti alla genovese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Gnocchi alla sorrentina', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pasta e patate (con provola)', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pasta e fagioli', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pasta e ceci', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pasta e lenticchie', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pasta e piselli', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Minestrone di verdure', 'Primo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Spaghetti alle vongole', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Linguine allo scoglio', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Spaghetti alla puttanesca', 'Primo', 'Pesce', 0, 'Carboidrati', 'Di Mare'),
('Spaghetti alla Nerano', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pasta alla Norma', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Orecchiette alle cime di rapa', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Busiate al pesto trapanese', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pasta con le sarde', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Anelletti al forno', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Malloreddus alla campidanese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Culurgiones al burro e salvia', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pansoti con salsa di noci', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Agnolotti del plin al sugo d''arrosto', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Casoncelli alla bergamasca', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Pizzoccheri alla valtellinese', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Canederli in brodo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Spätzle panna e speck', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Passatelli in brodo', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Maccheroni alla chitarra con pallottine', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Risotto alla milanese', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Risotto ai funghi porcini', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Di Terra'),
('Risotto al radicchio e gorgonzola', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Risotto agli asparagi', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Risotto alla pescatora', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Risotto alla zucca', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Risi e bisi', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Penne alla vodka', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Farfalle panna e salmone', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Penne alla boscaiola', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Maccheroni ai quattro formaggi', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Gnocchi al gorgonzola', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Gnocchi al ragù', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Ravioli ricotta e spinaci burro e salvia', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Cannelloni di carne al forno', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Calamarata', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Fregola con le arselle', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Pici all''aglione', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Pappardelle al ragù di cinghiale', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Ribollita', 'Primo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Pappa al pomodoro', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Zuppa di farro', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Gramigna alla salsiccia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Mezze maniche alla norcina', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Strangozzi al tartufo nero', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Di Terra'),
('Tajarin al tartufo bianco', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Di Terra'),
('Paniscia novarese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Pasta e cavolfiore', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Pasta e zucca', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Sedani con panna, prosciutto e piselli', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Spaghetti al tonno', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Penne zucchine e gamberetti', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Linguine all''astice', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Spaghetti con le cozze', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Risotto al nero di seppia', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Paccheri ai frutti di mare', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Fusilli peperoni e olive', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Spaghetti ai ricci di mare', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Pasta fredda (pomodorini, mozzarella, olive)', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Insalata di riso', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Orecchiette pomodoro e cacioricotta', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Gnocchi alla bava', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Maltagliati ai fagioli', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Bucatini coi cavolfiori alla siciliana', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Cavatelli con i broccoli', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Timballo di maccheroni', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Strozzapreti cannocchie e pomodorini', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Spaghetti con le telline', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Zuppa di lenticchie', 'Primo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Crema di zucca', 'Primo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Pasta e fagioli con le cozze', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Tubetti in brodo di gallina', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Paccheri con sugo di coccio', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Casarecce pesce spada e melanzane', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Gnocchetti sardi pomodoro e salsiccia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Scialatielli ai frutti di mare', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Mafalde con ricotta e pomodoro', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Spaghetti alla carrettiera', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Penne al baffo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Tagliatelle ai funghi misti', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Di Terra'),
('Risotto allo zafferano e salsiccia', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Agnolotti pavesi', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Anolini in brodo', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Bigoli in salsa', 'Primo', 'Pesce', 0, 'Carboidrati', 'Di Mare'),
('Cappelletti in brodo di cappone', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Casoncelli bresciani', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Cialzons', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Corzetti al sugo di carne', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Garganelli panna, piselli e prosciutto', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Gnocchi di susine', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Minestra d''orzo trentina', 'Primo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Panissa vercellese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Pisarei e faśö', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Risotto al Tastasal', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Risotto all''Amarone', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Di Terra'),
('Risotto all''isolana', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Risotto con la luganega', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Tajarin al ragù di fegatini', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Tortelli alle erbette', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Tortelli di zucca mantovani', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Acquacotta', 'Primo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Fettuccine alla papalina', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Maccheroncini di Campofilone', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Minestra di broccoli e arzilla', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Pappardelle alla lepre', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Sagne e fagioli', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Scrippelle ''mbusse', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Spaghetti alla checca', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Strangozzi (o Stringozzi) al ragù di agnello', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Testaroli al pesto', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Umbricelli al rancetto', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Vincisgrassi', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Zuppa frantoiana', 'Primo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Cavatelli cozze e fagioli', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Ciceri e tria', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Ferretti con mollica e cruschi', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Lagane e cicciari', 'Primo', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Maccheroni al ferretto con ragù lucano', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Orecchiette al ragù di braciole', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Spaghetti ai polipetti affogati', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Spaghetti alle vongole fujute', 'Primo', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Struncatura ammollicata', 'Primo', 'Pesce', 0, 'Carboidrati', 'Di Mare'),
('Tiella di riso, patate e cozze', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Tubetti con i totani', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Ziti lardiati', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Busiate al ragù di tonno', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Cuscus di pesce alla trapanese', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Fregola con salsiccia e zafferano', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Lorighittas al ragù di pollo ruspante', 'Primo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Maccarrones de busa', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Pasta alla Paolina', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Pasta ca nunnata', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Spaghetti alla bottarga', 'Primo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Zuppa gallurese', 'Primo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Bistecca di manzo ai ferri', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Cotoletta panata alla milanese', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Scaloppine ai funghi', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Petto di pollo alla griglia', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Polpette di carne al sugo', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Polpette di carne fritte', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Polpettone al forno', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Spezzatino con patate', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Arrosto di vitello', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Involtini di carne ripieni', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Salsiccia in padella', 'Secondo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Hamburger di carne', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Cosce di pollo al forno', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Orata al cartoccio', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Frittura di calamari e gamberi', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Trancio di salmone in padella', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Seppie con piselli', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Merluzzo in umido con pomodorini', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Frittata di cipolle', 'Secondo', 'Vegetariano', 0, 'Proteico', 'Vegetale'),
('Uova al tegamino', 'Secondo', 'Vegetariano', 0, 'Proteico', 'Vegetale'),
('Caprese di mozzarella e pomodoro', 'Secondo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Straccetti di manzo con rucola', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Pesce spada alla griglia', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Sgombro al forno', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Braciola di maiale', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Fesa di tacchino arrosto', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Bresaola con rucola e grana', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Prosciutto e melone', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Zucchine ripiene di carne', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Vegetale'),
('Peperoni ripieni', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Vegetale'),
('Roast beef all''inglese', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Insalata di mare', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Impepata di cozze', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Tonno scottato', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Spiedini di carne mista', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Faraona al forno', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Coniglio alla cacciatora', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Vitello tonnato', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Polpo con patate', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Calamari ripieni', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Gamberoni al forno', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Sogliola al burro', 'Secondo', 'Pesce', 0, 'Fibre e vitamine', 'Di Mare'),
('Tagliata di manzo', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Alici marinate', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Moscardini in umido', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Filetto di manzo al pepe verde', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Lonza di maiale arrosto', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Petto di tacchino in padella', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Carpaccio di manzo', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Tartare di manzo', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Cordon bleu di carne', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Costine di maiale al forno', 'Secondo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Branzino all''acqua pazza', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Alici fritte', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Calamari in padella', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Salsiccia e patate al forno', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Tomino alla piastra', 'Secondo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Scamorza alla griglia', 'Secondo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Uova sode ripiene', 'Secondo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Uova strapazzate', 'Secondo', 'Vegetariano', 0, 'Proteico', 'Vegetale'),
('Frittata di zucchine', 'Secondo', 'Vegetariano', 0, 'Proteico', 'Vegetale'),
('Cotechino con lenticchie', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Melanzane ripiene di carne', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Vegetale'),
('Sogliola alla mugnaia', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Pesce finto di tonno e patate', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Hamburger di pollo', 'Secondo', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Bistecca di tacchino', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Filetto di maiale arrosto', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Nodini di vitello al burro', 'Secondo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Uova in camicia', 'Secondo', 'Vegetariano', 0, 'Proteico', 'Vegetale'),
('Sarde alla piastra', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Filetto di platessa impanato', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Seppie arrosto', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Soutè di cozze e vongole', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Cotoletta di maiale', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Stinco di maiale al forno', 'Secondo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Rollè di tacchino ripieno', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Sovracosce di pollo in padella', 'Secondo', 'Carne Bianca', 0, 'Fibre e vitamine', 'Di Terra'),
('Bastoncini di pesce impanati', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Trancio di tonno al forno', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Fegato alla veneziana', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Arrosticini di pecora', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Coda alla vaccinara', 'Secondo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Saltimbocca alla romana', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Baccalà alla vicentina', 'Secondo', 'Pesce', 0, 'Fibre e vitamine', 'Di Mare'),
('Porceddu sardo', 'Secondo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Fritto misto alla piemontese', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Sarde in saor', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Braciole alla messinese', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Trippa alla fiorentina', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Bombette pugliesi', 'Secondo', 'Carne Rossa', 0, 'Fibre e vitamine', 'Di Terra'),
('Peposo dell''Impruneta', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Ossobuco alla milanese', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Cima alla genovese', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Frico friulano', 'Secondo', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Triglie alla livornese', 'Secondo', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Involtini di pesce spada alla siciliana', 'Secondo', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Gulasch trentino', 'Secondo', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Pollo alla romana', 'Secondo', 'Carne Bianca', 0, 'Proteico', 'Di Terra'),
('Brasato al Barolo', 'Secondo', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Patate al forno', 'Contorno', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Patate fritte', 'Contorno', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Purè di patate', 'Contorno', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Insalata di patate', 'Contorno', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Patate in padella', 'Contorno', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Zucchine alla griglia', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Melanzane a funghetto', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Peperonata', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Spinaci saltati in padella', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Cicoria ripassata', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Di Terra'),
('Fagiolini lessi', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Funghi trifolati', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Di Terra'),
('Cime di rapa stufate', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Di Terra'),
('Bieta all''agro', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Carciofi alla romana', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Di Terra'),
('Piselli in umido', 'Contorno', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Zucchine trifolate', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Finocchi gratinati', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Cavolfiore gratinato', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Zucca al forno', 'Contorno', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Pomodori gratinati', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Verdure miste al forno', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Fagioli all''uccelletto', 'Contorno', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Lenticchie in umido', 'Contorno', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Ceci in insalata', 'Contorno', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Insalata mista', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Insalata di finocchi', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Insalata di pomodori', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Puntarelle alla romana', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Di Mare'),
('Melanzane sott''olio', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Di Terra'),
('Zucchine alla scapece', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Giardiniera di verdure', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Carciofini sott''olio', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Di Terra'),
('Cipolline in agrodolce', 'Contorno', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Pizza', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Pinsa romana', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Focaccia ripiena', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Panzerotti pugliesi', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Piadina romagnola', 'Piatto Unico', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Tigelle con salumi e formaggi', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Torta al testo', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Crescia', 'Piatto Unico', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Panino con panelle', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Panino con salumi', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Pani ca meusa', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Tramezzino', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Toast', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Club sandwich', 'Piatto Unico', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Farinata di ceci', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Gateau di patate', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Torta pasqualina', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Quiche lorraine', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Torta salata ricotta e spinaci', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Strudel salato', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Danubio salato', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Babà rustico', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Casatiello', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Lasagna', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Cannelloni', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Sartù di riso', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Timballo di anelletti', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Pasta al forno', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Vincisgrassi', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Frittata di pasta', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Melanzane ripiene', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Peperoni ripieni', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Ragù napoletano', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Bollito misto con brodo', 'Piatto Unico', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Cacciucco alla livornese', 'Piatto Unico', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Brodetto di pesce', 'Piatto Unico', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Seppie con piselli', 'Piatto Unico', 'Pesce', 0, 'Proteico', 'Di Mare'),
('Spezzatino con patate', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Insalata di riso', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Insalata di pasta', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Panzanella', 'Piatto Unico', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Frisella condita', 'Piatto Unico', 'Vegetariano', 0, 'Carboidrati', 'Vegetale'),
('Insalatona mista', 'Piatto Unico', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Caprese', 'Piatto Unico', 'Vegetariano', 0, 'Fibre e vitamine', 'Vegetale'),
('Prosciutto e melone', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Carpaccio con rucola e grana', 'Piatto Unico', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Cous cous freddo', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Insalata nizzarda', 'Piatto Unico', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Polenta concia', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Di Terra'),
('Polenta e salsiccia', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Ribollita', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Minestrone con cereali', 'Piatto Unico', 'Vegetariano', 0, 'Carbo-Proteico', 'Vegetale'),
('Trippa alla romana', 'Piatto Unico', 'Carne Rossa', 0, 'Proteico', 'Di Terra'),
('Frittata di verdure', 'Piatto Unico', 'Vegetariano', 0, 'Proteico', 'Vegetale'),
('Hamburger', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Hot dog', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Kebab', 'Piatto Unico', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Burritos', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Tacos', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Poke bowl con Salmone', 'Piatto Unico', 'Pesce', 0, 'Carbo-Proteico', 'Di Mare'),
('Bao di carne', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Ravioli al vapore di carne(Jiaozi)', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra'),
('Paella valenciana', 'Piatto Unico', 'Carne Bianca', 0, 'Carbo-Proteico', 'Di Terra'),
('Moussaka', 'Piatto Unico', 'Carne Rossa', 0, 'Carbo-Proteico', 'Di Terra');
